import type { Influencer, AdRequest } from "./types";

const IMG = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=600&q=70`;

export const MOCK_INFLUENCERS: Influencer[] = [
  {
    id: "khaled-otaibi",
    name: "خالد العتيبي",
    phone: "0500000001",
    email: "khaled@example.com",
    city: "الدمام",
    category: "تقنية",
    bio: "صانع محتوى تقني متخصص في مراجعة الأجهزة الذكية والتطبيقات الحديثة، أمتلك جمهوراً مهتماً بالتكنولوجيا في المنطقة الشرقية.",
    followers: 125000,
    views: 4522,
    clicks: 340,
    ad_requests: 12,
    avatar_url: IMG("photo-1507003211169-0a1dd7228f2d"),
    gallery: [IMG("photo-1531297484001-80022131f5a1"), IMG("photo-1498050108023-c5249f4df085")],
    verified: true,
    status: "approved",
    socials: {
      instagram: "https://instagram.com",
      tiktok: "https://tiktok.com",
      x: "https://x.com",
      whatsapp: "https://wa.me/966500000001",
    },
  },
  {
    id: "fahd-anzi",
    name: "فهد العنزي",
    phone: "0500000002",
    email: "fahd@example.com",
    city: "القطيف",
    category: "رياضة",
    bio: "لاعب كرة قدم سابق ومعلق رياضي، أغطي الأحداث الرياضية المحلية والعالمية وأشارك تحليلات مباريات.",
    followers: 180000,
    views: 5403,
    clicks: 410,
    ad_requests: 18,
    avatar_url: IMG("photo-1519085360753-af0119f7cbe7"),
    gallery: [IMG("photo-1517649763962-0c623066013b")],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", x: "https://x.com", whatsapp: "https://wa.me/966500000002" },
  },
  {
    id: "abdullah-dosari",
    name: "عبدالله الدوسري",
    phone: "0500000003",
    email: "abdullah@example.com",
    city: "الظهران",
    category: "أعمال",
    bio: "خبير تسويق رقمي وريادة أعمال، أساعد الشركات الناشئة على النمو عبر استراتيجيات التسويق الحديثة.",
    followers: 210000,
    views: 6804,
    clicks: 520,
    ad_requests: 24,
    avatar_url: IMG("photo-1500648767791-00dcc994a43e"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", x: "https://x.com", whatsapp: "https://wa.me/966500000003" },
  },
  {
    id: "majed-shammari",
    name: "ماجد الشمري",
    phone: "0500000004",
    email: "majed@example.com",
    city: "الأحساء",
    category: "ترفيه",
    bio: "صانع محتوى ترفيهي وكوميدي، أنتج مقاطع مرحة تعكس الحياة اليومية بأسلوب فكاهي يجمع بين الثقافة المحلية.",
    followers: 350000,
    views: 9503,
    clicks: 720,
    ad_requests: 30,
    avatar_url: IMG("photo-1506794778202-cad84cf45f1d"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", snapchat: "https://snapchat.com", whatsapp: "https://wa.me/966500000004" },
  },
  {
    id: "sara-maliki",
    name: "سارة المالكي",
    phone: "0500000005",
    email: "sara@example.com",
    city: "الجبيل",
    category: "طبخ",
    bio: "شيف وطباخة محترفة، أشارك وصفات الطبخ الشرقي والحلويات مع لمسات عصرية. أستهدف عشاق الطعام.",
    followers: 67000,
    views: 2101,
    clicks: 150,
    ad_requests: 6,
    avatar_url: IMG("photo-1544005313-94ddf0286df2"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", whatsapp: "https://wa.me/966500000005" },
  },
  {
    id: "noura-qahtani",
    name: "نورة القحطاني",
    phone: "0500000006",
    email: "noura@example.com",
    city: "الخبر",
    category: "أزياء",
    bio: "مستشارة أزياء وموضة، أشارك أحدث صيحات الموضة والعناية بالجمال لجمهور نسائي في الخبر والمنطقة.",
    followers: 89000,
    views: 3212,
    clicks: 220,
    ad_requests: 9,
    avatar_url: IMG("photo-1534528741775-53994a69daeb"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", snapchat: "https://snapchat.com", whatsapp: "https://wa.me/966500000006" },
  },
];

export const MOCK_AD_REQUESTS: AdRequest[] = [
  {
    id: "req-1",
    company_name: "شركة النخبة للتجارة",
    contact_name: "محمد الحربي",
    phone: "0555555555",
    email: "info@nokhba.sa",
    category: "عقارات",
    city: "الظهران",
    details: "حملة إعلانية لمشروع عقاري جديد تستهدف جمهور المنطقة الشرقية.",
    budget: 50000,
    target_influencer: "عبدالله الدوسري",
    status: "pending",
  },
];
