import type { Influencer, AdRequest } from "./types";

const MEDIA = "https://media.base44.com/images/public/6a568a5faa72478f74107d31";
const IMG = (file: string) => `${MEDIA}/${file}`;

export const MOCK_INFLUENCERS: Influencer[] = [
  {
    id: "khaled-otaibi",
    name: "خالد العتيبي",
    phone: "0500000001",
    email: "khaled@example.com",
    city: "الدمام",
    category: "تقنية",
    bio: "صانع محتوى تقني متخصص في مراجعة الأجهزة الذكية والتطبيقات الحديثة، أمتلك جمهوراً مهتماً بالتكنولوجيا في المنطقة الشرقية.",
    followers: 125000,
    views: 4522,
    clicks: 340,
    ad_requests: 12,
    avatar_url: IMG("215e9e2cb_generated_a732d1bb.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: {
      instagram: "https://instagram.com",
      tiktok: "https://tiktok.com",
      x: "https://x.com",
      whatsapp: "https://wa.me/966500000001",
    },
  },
  {
    id: "fahd-anzi",
    name: "فهد العنزي",
    phone: "0500000002",
    email: "fahd@example.com",
    city: "القطيف",
    category: "رياضة",
    bio: "لاعب كرة قدم سابق ومعلق رياضي، أغطي الأحداث الرياضية المحلية والعالمية وأشارك تحليلات مباريات.",
    followers: 180000,
    views: 5403,
    clicks: 410,
    ad_requests: 18,
    avatar_url: IMG("4c6271fed_generated_a36d8b97.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", x: "https://x.com", whatsapp: "https://wa.me/966500000002" },
  },
  {
    id: "abdullah-dosari",
    name: "عبدالله الدوسري",
    phone: "0500000003",
    email: "abdullah@example.com",
    city: "الظهران",
    category: "أعمال",
    bio: "خبير تسويق رقمي وريادة أعمال، أساعد الشركات الناشئة على النمو عبر استراتيجيات التسويق الحديثة.",
    followers: 210000,
    views: 6804,
    clicks: 520,
    ad_requests: 24,
    avatar_url: IMG("b124c6474_generated_e435674f.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", x: "https://x.com", whatsapp: "https://wa.me/966500000003" },
  },
  {
    id: "majed-shammari",
    name: "ماجد الشمري",
    phone: "0500000004",
    email: "majed@example.com",
    city: "الأحساء",
    category: "ترفيه",
    bio: "صانع محتوى ترفيهي وكوميدي، أنتج مقاطع مرحة تعكس الحياة اليومية بأسلوب فكاهي يجمع بين الثقافة المحلية.",
    followers: 350000,
    views: 9503,
    clicks: 720,
    ad_requests: 30,
    avatar_url: IMG("f5807189d_generated_6fd903fe.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", snapchat: "https://snapchat.com", whatsapp: "https://wa.me/966500000004" },
  },
  {
    id: "sara-maliki",
    name: "سارة المالكي",
    phone: "0500000005",
    email: "sara@example.com",
    city: "الجبيل",
    category: "طبخ",
    bio: "شيف وطباخة محترفة، أشارك وصفات الطبخ الشرقي والحلويات مع لمسات عصرية. أستهدف عشاق الطعام.",
    followers: 67000,
    views: 2101,
    clicks: 150,
    ad_requests: 6,
    avatar_url: IMG("cbb551846_generated_6ce9632a.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", tiktok: "https://tiktok.com", whatsapp: "https://wa.me/966500000005" },
  },
  {
    id: "noura-qahtani",
    name: "نورة القحطاني",
    phone: "0500000006",
    email: "noura@example.com",
    city: "الخبر",
    category: "أزياء",
    bio: "مستشارة أزياء وموضة، أشارك أحدث صيحات الموضة والعناية بالجمال لجمهور نسائي في الخبر والمنطقة.",
    followers: 89000,
    views: 3212,
    clicks: 220,
    ad_requests: 9,
    avatar_url: IMG("690e8c301_generated_079913f0.png"),
    gallery: [],
    verified: true,
    status: "approved",
    socials: { instagram: "https://instagram.com", snapchat: "https://snapchat.com", whatsapp: "https://wa.me/966500000006" },
  },
];

export const MOCK_AD_REQUESTS: AdRequest[] = [
  {
    id: "req-1",
    company_name: "شركة النخبة للتجارة",
    contact_name: "محمد الحربي",
    phone: "0555555555",
    email: "info@nokhba.sa",
    category: "عقارات",
    city: "الظهران",
    details: "حملة إعلانية لمشروع عقاري جديد تستهدف جمهور المنطقة الشرقية.",
    budget: 50000,
    target_influencer: "عبدالله الدوسري",
    status: "pending",
  },
];
